name: Docker Image CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.0.0
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
    - name: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: appsettings.json 
        json: ${{secrets.APPSETTINGS}} 
        dir: ./WebAPI
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8
      uses: docker/build-push-action@v3.0.0
      with:
        context: .
        file: ./Dockerfile
        tags: index.docker.io/${{secrets.DOCKERHUB_USERNAME}}/garagemeet:${{github.sha}}
        push: true
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: 'garagemeet'
        publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE_GARAGEMEET}}
        images: index.docker.io/${{secrets.DOCKERHUB_USERNAME}}/garagemeet:${{github.sha}}

